// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFolderFilepaths(arg1:string):Promise<string>;

export function GetLocalFile(arg1:string):Promise<string>;

export function GetThumbnailAsBase64(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function GreetJohn(arg1:string):Promise<string>;
