// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFolderFilepaths(arg1) {
  return window['go']['main']['App']['GetFolderFilepaths'](arg1);
}

export function GetLocalFile(arg1) {
  return window['go']['main']['App']['GetLocalFile'](arg1);
}

export function GetThumbnailAsBase64(arg1) {
  return window['go']['main']['App']['GetThumbnailAsBase64'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function GreetJohn(arg1) {
  return window['go']['main']['App']['GreetJohn'](arg1);
}
