// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatDate(arg1, arg2) {
  return window['go']['main']['App']['FormatDate'](arg1, arg2);
}

export function GetFileDetailsSingle(arg1) {
  return window['go']['main']['App']['GetFileDetailsSingle'](arg1);
}

export function GetFileMeta(arg1) {
  return window['go']['main']['App']['GetFileMeta'](arg1);
}

export function GetFolderAPI(arg1) {
  return window['go']['main']['App']['GetFolderAPI'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetListView(arg1) {
  return window['go']['main']['App']['GetListView'](arg1);
}

export function GetLocalFile(arg1) {
  return window['go']['main']['App']['GetLocalFile'](arg1);
}

export function GetSubDirPaths(arg1) {
  return window['go']['main']['App']['GetSubDirPaths'](arg1);
}

export function GetThumbnailAsBase64(arg1) {
  return window['go']['main']['App']['GetThumbnailAsBase64'](arg1);
}

export function GetTree(arg1) {
  return window['go']['main']['App']['GetTree'](arg1);
}

export function GetTreeHTML(arg1) {
  return window['go']['main']['App']['GetTreeHTML'](arg1);
}

export function OpenWithDefaultApp(arg1) {
  return window['go']['main']['App']['OpenWithDefaultApp'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SetFileMeta(arg1, arg2) {
  return window['go']['main']['App']['SetFileMeta'](arg1, arg2);
}
