// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FormatDate(arg1, arg2) {
  return window['go']['main']['App']['FormatDate'](arg1, arg2);
}

export function GetFolderAPI(arg1) {
  return window['go']['main']['App']['GetFolderAPI'](arg1);
}

export function GetLocalFile(arg1) {
  return window['go']['main']['App']['GetLocalFile'](arg1);
}

export function GetThumbnailAsBase64(arg1) {
  return window['go']['main']['App']['GetThumbnailAsBase64'](arg1);
}

export function OpenWithDefaultApp(arg1) {
  return window['go']['main']['App']['OpenWithDefaultApp'](arg1);
}
